// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-v4KECErbZsU4FnRziXV9oGnGpMxSGrQ',
    appId: '1:648897886498:web:9c06e1bbec4a2d893bcd7b',
    messagingSenderId: '648897886498',
    projectId: 'busbee-c492e',
    authDomain: 'busbee-c492e.firebaseapp.com',
    databaseURL: 'https://busbee-c492e-default-rtdb.firebaseio.com',
    storageBucket: 'busbee-c492e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD53DiDjI7vXYmxjRwEm7LdtUlxODBkFhU',
    appId: '1:648897886498:android:4e54f1aced3671d33bcd7b',
    messagingSenderId: '648897886498',
    projectId: 'busbee-c492e',
    databaseURL: 'https://busbee-c492e-default-rtdb.firebaseio.com',
    storageBucket: 'busbee-c492e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOetDU2tA2U4HprDpTZ7s8QjYCWb9_i1E',
    appId: '1:648897886498:ios:7cc753c33a2da2453bcd7b',
    messagingSenderId: '648897886498',
    projectId: 'busbee-c492e',
    databaseURL: 'https://busbee-c492e-default-rtdb.firebaseio.com',
    storageBucket: 'busbee-c492e.firebasestorage.app',
    iosBundleId: 'com.example.busbeePassenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOetDU2tA2U4HprDpTZ7s8QjYCWb9_i1E',
    appId: '1:648897886498:ios:7cc753c33a2da2453bcd7b',
    messagingSenderId: '648897886498',
    projectId: 'busbee-c492e',
    databaseURL: 'https://busbee-c492e-default-rtdb.firebaseio.com',
    storageBucket: 'busbee-c492e.firebasestorage.app',
    iosBundleId: 'com.example.busbeePassenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-v4KECErbZsU4FnRziXV9oGnGpMxSGrQ',
    appId: '1:648897886498:web:eb317584168970b23bcd7b',
    messagingSenderId: '648897886498',
    projectId: 'busbee-c492e',
    authDomain: 'busbee-c492e.firebaseapp.com',
    databaseURL: 'https://busbee-c492e-default-rtdb.firebaseio.com',
    storageBucket: 'busbee-c492e.firebasestorage.app',
  );
}
